version: '3'

services:
  app:
    build: .
    ports:
      - "9001:4000"
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fsdb
    volumes:
      - mysql_data:/var/lib/mysql

  jenkins:
    image: jenkins/jenkins:lts
    user: root                  # 🔥 IMPORTANT
    privileged: true            # 🔥 IMPORTANT
    ports:
      - "5001:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # 🔥 FIXED INDENT
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    dns:
      - 8.8.8.8
      - 1.1.1.1

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    # volumes:
    # - /var/jenkins_home/workspace/student-teacher-devops/prometheus.yml:/etc/prometheus/prometheus.yml
   

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  mysql_data:
  jenkins_home: