version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fsdb
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "5005:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    #   - ./prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - app-network

volumes:
  mysql_data:
  jenkins_home:

networks:
  app-network: