services:
  app:
    build: .
    ports:
      - "4020:4000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    restart: always
    networks:
      - app-network

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fsdb
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "5020:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9092:9090"
    volumes:
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3022:3000"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql_data:
  jenkins_home:
  prometheus_data:

networks:
  app-network: